name: dash_chat_custom
description: The most complete Chat UI for flutter. Easy to use, highly customizable and fully featured
version: 0.0.33
homepage: https://github.com/YusufElnaggar/dash-chat-custom

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.1
  flutter_parsed_text: ^2.2.1
  intl: ^0.20.2
  url_launcher: ^6.0.10
  uuid: ^4.5.1
  video_player: ^2.9.5
  chewie: ^1.11.3
#  better_player_plus: ^1.0.8
  widget_zoom_pro: ^0.0.6
  zoom_tap_animation: ^1.1.0
  #widget_zoom_pro:
  #  path: E:/PROYECTOS/FLUTTER/GITHUB/widget_zoom_pro/

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows: